# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\"$\n\x0fRegisterRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"9\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\"$\n\x0fGetModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"6\n\rModelResponse\x12\x14\n\x0cround_number\x18\x01 \x01(\x05\x12\x0f\n\x07weights\x18\x02 \x01(\x0c\"b\n\x11LocalModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x0f\n\x07weights\x18\x03 \x01(\x0c\x12\x13\n\x0bnum_samples\x18\x04 \x01(\x05\"\xa2\x01\n\x0eMetricsRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x0c\n\x04loss\x18\x03 \x01(\x02\x12\x0f\n\x07roc_auc\x18\x04 \x01(\x02\x12\x11\n\tprecision\x18\x05 \x01(\x02\x12\x0e\n\x06recall\x18\x06 \x01(\x02\x12\x10\n\x08\x66\x31_score\x18\x07 \x01(\x02\x12\x13\n\x0b\x64rift_score\x18\x08 \x01(\x02\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb6\x02\n\x11\x46\x65\x64\x65ratedLearning\x12I\n\x0eRegisterClient\x12\x1a.federated.RegisterRequest\x1a\x1b.federated.RegisterResponse\x12\x46\n\x0eGetGlobalModel\x12\x1a.federated.GetModelRequest\x1a\x18.federated.ModelResponse\x12I\n\x0eSendLocalModel\x12\x1c.federated.LocalModelRequest\x1a\x19.federated.UpdateResponse\x12\x43\n\x0bSendMetrics\x12\x19.federated.MetricsRequest\x1a\x19.federated.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=30
  _globals['_REGISTERREQUEST']._serialized_end=66
  _globals['_REGISTERRESPONSE']._serialized_start=68
  _globals['_REGISTERRESPONSE']._serialized_end=125
  _globals['_GETMODELREQUEST']._serialized_start=127
  _globals['_GETMODELREQUEST']._serialized_end=163
  _globals['_MODELRESPONSE']._serialized_start=165
  _globals['_MODELRESPONSE']._serialized_end=219
  _globals['_LOCALMODELREQUEST']._serialized_start=221
  _globals['_LOCALMODELREQUEST']._serialized_end=319
  _globals['_METRICSREQUEST']._serialized_start=322
  _globals['_METRICSREQUEST']._serialized_end=484
  _globals['_UPDATERESPONSE']._serialized_start=486
  _globals['_UPDATERESPONSE']._serialized_end=519
  _globals['_FEDERATEDLEARNING']._serialized_start=522
  _globals['_FEDERATEDLEARNING']._serialized_end=832
# @@protoc_insertion_point(module_scope)
